### ISSUE TITLE
setDrawRange doesn't cap the map as expected?

### ISSUE THREAD

**Issue by bitinn** [karai17/Simple-Tiled-Implementation#102]
I thought `setDrawRange` is as simple as setting a visible viewport where top-left origin has the tx,ty value and width/height is w,h.

But it doesn't appear to do anything under LOVE v0.10.1.

I looked at the source and your old tech demo, they appear to do what I expect, so is this a bug?

What's the expected output when I do this?

```
map:setDrawRange(0, 0, 200, 200)
map:draw()
```

**Comment by karai17** [comment]
The expected result is that the sprite batches that sit within the 0,0 ->
200,200 box should be drawn (even if the parts that are out of bounds).
Make sure to translate your camera using love.graphics.translate, or
whichever camera module you may be using, as sti does not have a built-in
camera.


---
Landon Manning
lmanning17@gmail.com

**Comment by bitinn** [comment]
Thing is, if STI doesn't have a camera, what is 0,0 relative to? screen? camera?

```
map:setDrawRange(0, 0, 200, 200)
map:draw()
```

I expect it to cap the map in a 200x200 square at the top-left of my screen, but it doesn't.

`love.graphics.push/trasnlate/pop` does what I expect, but combine them with `map:setDrawRange` I get results I can't seem to understand.

**Comment by karai17** [comment]
LOVE's fixed screen space.


---
Landon Manning
lmanning17@gmail.com

**Comment by bitinn** [comment]
OK I feel like I am barking at the wrong tree at this point.

All I want is to clip the rendered map to the top-half of the screen, I feel `setDrawRange` isn't for that. I should probably use something like `love.graphics.stencil` instead.

`setDrawRange` is intended for culling beyond the visible screen, can I set it to cull what's visible on screen? I mean clip, mask, crop or whatever term you prefer.

PS: I tried both `love.graphics` and `hump.camera` at this point, and they do exactly what I expect, but I can never get STI to clip the map properly, I feel like I missed something important, like telling STI *where camera is pointing at* etc.

```lua
-- main.lua

local STI = require('modules/sti')
local HumpCamera = require('modules/hump.camera')
local map, cam
local screen_width, screen_height

-- init
function love.load()
	screen_width = love.graphics.getWidth()
	screen_height = love.graphics.getHeight()
	map = STI.new('maps/test.lua')
	cam = HumpCamera.new(math.ceil(screen_width / 2), math.ceil(screen_height / 2), 1)
end

-- update loop
function love.update(dt)
	map:update(dt)
end

-- draw loop
function love.draw()
	cam:attach()
	-- how to clip the map on screen to the top half?
	--map:setDrawRange(0, 0, 200, 200)
	map:draw()
	cam:detach()

	-- fps meter
	love.graphics.print(tostring(love.timer.getFPS())..' FPS', 10, 10)
end
```

**Comment by karai17** [comment]
STI has no clipping functionality, only culling. What I believe you are
looking for is https://www.love2d.org/wiki/love.graphics.setScissor. This
creates a mask that cannot be drawn outside of. Combining this with
setDrawRange should give you the results you want.


---
Landon Manning
lmanning17@gmail.com

**Comment by pevzi** [comment]
setDrawRange ensures that STI will only draw the SpriteBatches that are currently visible in the given viewport to avoid unnecessary draw calls. It's a performance concern so it would be reasonable to combine it with the aforementioned setScissor anyway.

**Comment by bitinn** [comment]
@karai17 @pevzi Thx guys! Finally got it working.

I wonder if there are any ways to debug which tiles are being drawn, so I know I am using `setDrawRange` properly.

**Comment by karai17** [comment]
Just disable the scissor and move your camera around to make sure that draw
range is drawing what you expect. You can also set love.graphics.scale to
something less than 1 to zoom out and see more area.


---
Landon Manning
lmanning17@gmail.com

**Comment by rosshadden** [comment]
I think it's possible this is a documentation issue.  I have the same expectation problem.

The (now slightly outdated) blog post [here](http://lua.space/gamedev/using-tiled-maps-in-love) says to use `love.graphics.scale` and `love.graphics.translate`.  These work just as I would expect, and everything is perfect.  But the README here suggests using `map:setDrawRange`, and I can't figure out whether or not they are all meant to be used together.

By experimenting, I seem to have gotten it to work, but I made two changes that make me question whether it is working correctly:

1. I use `map:setDrawRange(0, 0, windowWidth, windowHeight)`, where the first two params are always hardcoded to `0`.  This goes against what the README says, as it has `-translateX` and `-translateY`.  Yet doing this causes everything to break in strange ways.
2. I have to set the `windowWidth/Height` to the full width/height, and not the width/height divided by the `scale`.  This goes against what the blog post says, as it sets width/height variables to `love.graphics.getWidth() / scale`.

Since neither example has both `love.graphics.translate` and `map:setDrawRange`, I think maybe the solution to our issue is to add an example to the docs.  Hope this cleared some things up!

**Comment by karai17** [comment]
setDrawRange is just a check to see which sprite batches to draw, it doesn't do anything more than that. When you translate the love coordinate space (the preferred way to "move" the map), you need to pass in your translation vector (tx, ty) to setDrawRange so that it know to only draw sprite batches that are visible on screen. This is all about culling, and not about cutting.

**Comment by rosshadden** [comment]
Consider this minimal example:

```lua
scale = 2
windowWidth = love.graphics.getWidth()
windowHeight = love.graphics.getHeight()
tx = math.floor(player.x - windowWidth / scale / 2)
ty = math.floor(player.y - windowHeight / scale / 2)

love.graphics.scale(scale)
love.graphics.translate(-tx, -ty)

map:setDrawRange(-tx, ty, windowWidth, windowHeight)
map:draw()
```

This actually clips the map, and only shows a small percentage of it.  Everything passed that clip point is black.

If I set `windowWidth/Height` to include the `scale` factor so that `setDrawRange` uses it, and remove it from `tx/ty`, it's even more crazy.  The map will be truncated like before, but moving passed a certain point will instantly turn everything black, and moving back the other way will instantly draw the (truncated) map again once that point is crossed.

**Comment by rosshadden** [comment]
I can provide screenshots if these explanations aren't cutting it.

**Comment by karai17** [comment]
Please do

**Comment by rosshadden** [comment]
Please let me know if you want to me to try anything else.  Hopefully I'm just doing something stupid!

With `setDrawRange(0, 0, windowWidth, windowHeight)`:
![2016-08-19-12 10 46](https://cloud.githubusercontent.com/assets/669012/17816212/0f0cc520-6606-11e6-8271-912ab937c8c0.png)

With `setDrawRange(-tx, -ty, windowWidth, windowHeight)`:
![2016-08-19-12 12 08](https://cloud.githubusercontent.com/assets/669012/17816237/2e8ce16e-6606-11e6-854a-54a1206e1196.png)

With `setDrawRange(-tx, -ty, windowWidth / scale, windowHeight / scale)`:
![2016-08-19-12 13 54](https://cloud.githubusercontent.com/assets/669012/17816274/6c8cc0d8-6606-11e6-88da-417ca808e3db.png)

The same code as above, but with me moving the player down a few pixels (everything vanishes until I move him back up):
![2016-08-19-12 14 15](https://cloud.githubusercontent.com/assets/669012/17816289/7a2828cc-6606-11e6-9d55-ae302ba52e71.png)

**Comment by karai17** [comment]
The code in my luaspace tutorial works. Try comparing it against your own code and seeing if there is a discrepancy?

**Comment by rosshadden** [comment]
The difference is that you aren't calling `map:setDrawRange` in your luaspace tutorial.

**Comment by karai17** [comment]
Hm. I'll have to look into this over the weekend. Can you send me a .love
file where you're getting the error?


---
Landon Manning
lmanning17@gmail.com

**Comment by rosshadden** [comment]
There's not an error thrown, and the behavior I explained depends on the code changes I mentioned.  I think it might be more useful if you could point me to a working example that uses `love.graphics.scale`, `love.graphics.translate`, and `map.setDrawRange`.  That way it would put the work of figuring out what's wrong on me, not you.

**Comment by karai17** [comment]
This seems to work fine, check out `L138` in `/gamestates/gameplay.lua`

https://www.dropbox.com/s/6yrdfqm63w8dfmw/sti-platform-new.love?dl=1

You will note that when you set scale to 0.5, you only see half the screen (which makes sense, since it is scaled!) and if you set it to 1.5, you are never shown any empty patches.

**Comment by karai17** [comment]
It seems like my readme is wrong, it should be tx and ty, not -tx and -ty for setDrawRange. I'll fix that.

**Comment by rosshadden** [comment]
Oh, that was the issue.  Using positive `tx` and `ty` works exactly as expected. Thanks!
