### ISSUE TITLE
Proposal: make map:clip() an alias of map:resize() 

### ISSUE THREAD

**Issue by bitinn** [karai17/Simple-Tiled-Implementation#104]
From what I can see, `map:resize()` does what we want in #102, and save all those manual `setScissor` / `setDrawRange`, is it good use case of `resize`, to clip the map? How's its performance comparing to manual setDrawRange?

**Comment by karai17** [comment]
map:resize does not replace map:setDrawRange. You need setDrawRange to cull out-of-screen batches to stop the from drawing altogether. resize could be used instead of setScissor, but it's not really set up for that. resize just takes in the size (width, height) of the canvas whereas setScissor sets a specific place where drawing is allowed (x, y, width, height). resize could be changed to mimic setScissor, but it would add complexity to the whole function to accommodate an edge case, which I don't think is a good idea.

**Comment by bitinn** [comment]
Interesting, so you are saying when I try to handle `love.resize` event with `map:resize`, the map is still culled using the original screen size? I feel that's a desirable feature, no?

**Comment by karai17** [comment]
No culling happens unless you use setDrawRange. Resizing only changes the canvas being drawn to, it does not affect performance in any way. You need to use setDrawRange to determine which batches should be drawn.

**Comment by bitinn** [comment]
You mean even if the canvas is small and we are mostly drawing outside of it, we still get performance penalty?

**Comment by karai17** [comment]
Yes. Drawing takes time, whether the results are shown or not.

**Comment by bitinn** [comment]
Good to know, closing this
