### ISSUE TITLE
Get nil just requiring sti

### ISSUE THREAD

**Issue by nyenye** [karai17/Simple-Tiled-Implementation#109]
When I try to do sti.new(), it crashes saying that sti is nil. I just started yesterday with Lua and Löve2d and I was following your tutorial (http://lua.space/gamedev/using-tiled-maps-in-love) and I assume that it should work :(

![issue_sti](https://cloud.githubusercontent.com/assets/11387253/15984140/89123c84-2faf-11e6-895b-48a7a8f46926.png)

Thanks for your hard work!

**Comment by karai17** [comment]
Hi! Welcome to LOVE and Lua!

So first off, when you require a module into Lua, you should use dot notation, not slashes.

```lua
local sti = require "lib.sti"
```

Second, though this is not a real issue, you can simply type `local map` since it's default value is `nil`.

Third, you need to send the full filename to sti, including the extension.

```lua
map = sti.new("assets/maps/map.lua")
```

Let me know if switchign from `/` to `.` fixes it for you.

**Comment by nyenye** [comment]
Heey, thanks a lot for the tips!

On the issue, it still persists. And the module should be loaded, given that when I change the require to a non existent module, i fails to load (as expected).

![imp_pant](https://cloud.githubusercontent.com/assets/11387253/15984237/c770ee04-2fb3-11e6-86ed-74d522c024d8.png)

The acutal error:

![issue_sti](https://cloud.githubusercontent.com/assets/11387253/15984216/49a90ede-2fb3-11e6-9760-e3ae76c14dd8.png)

**Comment by karai17** [comment]
`local sti **=** require "lib.sti"`

**Comment by nyenye** [comment]
Ok, now I just feel stupid :D. Thanks a lot again a best of luck!
