### ISSUE TITLE
Updating every tile each update limits map size severly

### ISSUE THREAD

**Issue by zorfmorf** [karai17/Simple-Tiled-Implementation#179]
Maybe I'm doing something wrong, but as far as I can tell, the implementation keeps a list of all the tiles and runs an update for each of the tiles on each update:

        function Map:update(dt)
	        for _, tile in pairs(self.tiles) do
		        local update = false
                        
		        if tile.animation then
			        [[ SNIP do update stuff ]]
		        end
	        end
                
                [[ SNIP update layers ]]
        end

In my example I have a 300x300 map with exactly one tile with animations. The draw function performs fine and simply draws what's on the screen, but the update function updating for every single one of 90000 tiles (when there is nothing do for all but one of them) makes performance on update so bad that it's unusable. 

I see two ways of handling this:

1. Animations should only be updated for tiles that are actually on (near) the screen
2. Only keep a global list of tiles with actual animations and only update these each update frame

**Comment by karai17** [comment]
I amunsure what the issue you are having is because animated tiles are already working like this. Though they do update even if they are off screen, only tiles flagged as animated run the animation update. It only updates global tiles and then updates the sprite batches necessary when an animation needs a new frame, so it shodul be about as fast as it can be.

**Comment by zorfmorf** [comment]
The issue is, that it runs a "if tile has animation" check for each tile on each update. So if you have a 1000x1000 tile map, that's one million unnecessary checks on each update cycle. This leads to severe fps drops on lower end devices. Commenting out the above for-loop fixes the issue for me. I have a local solution where I just save all tiles with animations into a list on map initialization and then only iterate over this list on on update instead of looping over all tiles.

**Comment by karai17** [comment]
Hm. I can see your point. Building an animated table would definitely be magnitudally faster. There needs to be a mechanism in place for when tiles are modified to check if they are animated so that they can be added or removed from the lookup table.

**Comment by zorfmorf** [comment]
I have a solution that implements that. I'll clean it up and create a pull request if you're interested

**Comment by karai17** [comment]
that would be wonderful :)

**Comment by karai17** [comment]
No PR ever came so I am going to close this issue. Since this was last discussed, Tiled has implemented Infinite Maps which (currently) won't resolve this, but I may add support for chunk culling to Infinite Maps at a later date (or if someone wants to send a PR..)

In the mean time, I think a more viable solution to this would be to break your world up into smaller map files. Tiled now supports "Worlds" which allows you to edit multiple maps in a single Tiled tab, and STI allows for loading maps with offsets, so I'm sure there is a solution in there somewhere too.
