### ISSUE TITLE
Walk behind and in front of walls

### ISSUE THREAD

**Issue by maluramichael** [karai17/Simple-Tiled-Implementation#185]
I cannot find any example for walls. No matter what my character is walking above or underneath my walls. You can see this behavior in my example here: [test.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/2224474/collision_test.zip)

I searched the web and some said one have to sort that specific layer by the y coordinate according to the player position.

Has someone an example or some hints how to archive the correct behavior?

**Comment by karai17** [comment]
https://github.com/excessive/rpg/blob/896aa795959a6810a5bd59891b60c4fa851a90ec/states/gameplay.lua#L236

You effectively want to gather up all your "sortable" objects and sort them by their `y` value and then draw them in order, that way things with a smaller `y` value will get drawn first, thus underneath the other things in the list.

It's a bit more complicated with general terrain such as cave walls so you may need to make the walls into objects instead of normal tile layers. But with standard objects like trees or bushes, it's not so bad.
