### ISSUE TITLE
Tile object shape position

### ISSUE THREAD

**Issue by Cowa** [karai17/Simple-Tiled-Implementation#60]
Hi,

**Tile objects shape** are not at the right position. But the tile itself is ok.

Some screenshots to illustrate:

**In editor**
![oneditor](https://cloud.githubusercontent.com/assets/1422403/4847917/46220d3e-6056-11e4-8eae-8b1b42285d14.png)

**In game**
![ongame](https://cloud.githubusercontent.com/assets/1422403/4847918/47b4637c-6056-11e4-912b-907deb9ea10a.png)
The shape is drawn below the tile

**Comment by Cowa** [comment]
Hi !

Sorry for the delay, but the bug is still here.

I made a simple project to demonstrate the bug, you can check it by yourself : 
https://www.dropbox.com/s/2hliqjahe6d6xkv/tileObjectShapeBug.zip?dl=0

**Comment by karai17** [comment]
Hey, I think I just fixed the bug! Please download 0.9.6 and let me know if it works for you.

**Comment by Cowa** [comment]
It's fixed !

:+1:

**Comment by karai17** [comment]
Okay so I found the actual issue. For some reason your tile object has a width and height when it should not. Tiles are drawn with a -h offset because they are positioned form the bottom left instead of top left whereas normal objects are not. This was causing the tile to be drawn properly whereas the "rectangle" was being drawn without the tile offset.

I have corrected this and now rectangle objects with a tile gid will be drawn in the appropriate spot, though to be honest they shouldn't be drawn at all!
